version: 0.2
phases:
  
  pre_build:
    commands:
      - mkdir -p python 
      - pip install -t ./python  -r requirements.txt 
      - cd python
      - zip -r req_build_layer.zip *
      - mv req_build_layer.zip ../
      - cd .. 
      - chmod 777 req_build_layer.zip
      - ls
      - pwd
  build:
    commands:
      - ls
      - pwd
      - aws sam package --template-file samTemplate.yaml --s3-bucket disney-cicd --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
