version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket disney-cicd --output-template-file outputSamTemplate.yaml
  pre_build:
    commands:
      - pip install -t ./python  -r requirements.txt
      - zip -r  ./python -i req_build_layer
      - ls 
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
