AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Disney
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::897913520775:role/lambda_basic_execution'
      Layers: 
        - !Ref LambdaLayer
      Environment:
        Variables:
          REGION: us-east-1
      
  LambdaLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties: 
      LayerName: request_build_layer
      ContentUri: 'request_build_layer.zip'
      ComptabileRuntimes:
        - Python3.7
      LicenseInfo: MIT
      RetentionPolicy: Retain
        
      
